---
# tasks file for bvansomeren.lldpd
- name: ensure lldpd is installed
  package: 
    name: "{{ lldp_package_name[ansible_os_family] }}" 
    state: present
  register: reg_lldpd_install_package
  when: 
    - lldp_enable
    - ansible_virtualization_role != "guest" or ansible_virtualization_role != "NA"

- name: ensure lldpd is started and available at boot
  service: 
    name: "{{ lldp_service_name[ansible_os_family] }}" 
    state: started 
    enabled: yes
  when: 
    - lldp_enable
    - ansible_virtualization_role != "guest" or ansible_virtualization_role != "NA"

- name: transmit tlvs with lldptool on RedHat if we just installed lldpd
  command: "lldptool -i {{ item[0] }} -T -V {{ item[1].id }} enableTx={{ item[1].enableTx }}"
  with_nested: 
    - "{{ ansible_interfaces }}"
    - "{{ lldp_tlvs }}"
  when: 
    - lldp_enable # defaults to True
    - lldp_transmit_sysname  # defaults to True
    - ansible_{{ item[0] }}['active'] == true # only active interfaces
    - (ansible_{{ item[0] }}['type'] != "loopback" and ansible_{{ item[0] }}['type'] is defined) # IB interfaces has no type with ansible 2.2
    - item[0] in lldp_sysname_interfaces # this list only has "em1" by default
    - reg_lldpd_install_package.changed or lldp_sysname_force is defined # only when we just installed lldp or if lldp_sysname_force is defined
    - ansible_os_family == "RedHat"
    - ansible_virtualization_role != "guest" or ansible_virtualization_role != "NA" # not on virtual machines or where ansible can't detect
  notify:
    - restart lldpad
