---
# tasks file for bvansomeren.lldpd
- name: ensure lldpd is installed
  package: name="{{ lldp_package_name[ansible_os_family] }}" state=present

- name: ensure lldpd is started and available at boot
  service: name="{{ lldp_service_name[ansible_os_family] }}" state=started enabled=yes

